# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'junction.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Junction(object):
    def setupUi(self, Junction):
        Junction.setObjectName("Junction")
        Junction.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Junction.sizePolicy().hasHeightForWidth())
        Junction.setSizePolicy(sizePolicy)
        Junction.setMinimumSize(QtCore.QSize(640, 480))
        self.centralWidget = QtWidgets.QWidget(Junction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTab = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTab.setObjectName("mainTab")
        self.Wallet = QtWidgets.QWidget()
        self.Wallet.setObjectName("Wallet")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Wallet)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.Wallet)
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.walletNameLabel = QtWidgets.QLabel(self.widget)
        self.walletNameLabel.setObjectName("walletNameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.walletNameLabel)
        self.walletNameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.walletNameLineEdit.setObjectName("walletNameLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.walletNameLineEdit)
        self.requiredSignersLabel = QtWidgets.QLabel(self.widget)
        self.requiredSignersLabel.setObjectName("requiredSignersLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.requiredSignersLabel)
        self.requiredSignersLineEdit = QtWidgets.QLineEdit(self.widget)
        self.requiredSignersLineEdit.setObjectName("requiredSignersLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.requiredSignersLineEdit)
        self.totalSignersLabel = QtWidgets.QLabel(self.widget)
        self.totalSignersLabel.setObjectName("totalSignersLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.totalSignersLabel)
        self.totalSignersLineEdit = QtWidgets.QLineEdit(self.widget)
        self.totalSignersLineEdit.setObjectName("totalSignersLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.totalSignersLineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.verticalLayout_3.addWidget(self.widget)
        self.mainTab.addTab(self.Wallet, "")
        self.Devices = QtWidgets.QWidget()
        self.Devices.setObjectName("Devices")
        self.mainTab.addTab(self.Devices, "")
        self.Settings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings.sizePolicy().hasHeightForWidth())
        self.Settings.setSizePolicy(sizePolicy)
        self.Settings.setObjectName("Settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Settings)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rPCSettingsWidget = QtWidgets.QWidget(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPCSettingsWidget.sizePolicy().hasHeightForWidth())
        self.rPCSettingsWidget.setSizePolicy(sizePolicy)
        self.rPCSettingsWidget.setObjectName("rPCSettingsWidget")
        self.formLayout = QtWidgets.QFormLayout(self.rPCSettingsWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.rPCUsernameLabel = QtWidgets.QLabel(self.rPCSettingsWidget)
        self.rPCUsernameLabel.setObjectName("rPCUsernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rPCUsernameLabel)
        self.rPCUsernameLineEdit = QtWidgets.QLineEdit(self.rPCSettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPCUsernameLineEdit.sizePolicy().hasHeightForWidth())
        self.rPCUsernameLineEdit.setSizePolicy(sizePolicy)
        self.rPCUsernameLineEdit.setObjectName("rPCUsernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rPCUsernameLineEdit)
        self.rPCPasswordLabel = QtWidgets.QLabel(self.rPCSettingsWidget)
        self.rPCPasswordLabel.setObjectName("rPCPasswordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rPCPasswordLabel)
        self.rPCPasswordLineEdit = QtWidgets.QLineEdit(self.rPCSettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPCPasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.rPCPasswordLineEdit.setSizePolicy(sizePolicy)
        self.rPCPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rPCPasswordLineEdit.setObjectName("rPCPasswordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rPCPasswordLineEdit)
        self.rPCHostLabel = QtWidgets.QLabel(self.rPCSettingsWidget)
        self.rPCHostLabel.setObjectName("rPCHostLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rPCHostLabel)
        self.rPCHostLineEdit = QtWidgets.QLineEdit(self.rPCSettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPCHostLineEdit.sizePolicy().hasHeightForWidth())
        self.rPCHostLineEdit.setSizePolicy(sizePolicy)
        self.rPCHostLineEdit.setObjectName("rPCHostLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rPCHostLineEdit)
        self.rPCPortLabel = QtWidgets.QLabel(self.rPCSettingsWidget)
        self.rPCPortLabel.setObjectName("rPCPortLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rPCPortLabel)
        self.rPCPortLineEdit = QtWidgets.QLineEdit(self.rPCSettingsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rPCPortLineEdit.sizePolicy().hasHeightForWidth())
        self.rPCPortLineEdit.setSizePolicy(sizePolicy)
        self.rPCPortLineEdit.setObjectName("rPCPortLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rPCPortLineEdit)
        self.RPCSettingsDialog = QtWidgets.QDialogButtonBox(self.rPCSettingsWidget)
        self.RPCSettingsDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RPCSettingsDialog.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.RPCSettingsDialog.setObjectName("RPCSettingsDialog")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.RPCSettingsDialog)
        self.verticalLayout_2.addWidget(self.rPCSettingsWidget)
        self.currentRPCSettingsLabel = QtWidgets.QLabel(self.Settings)
        self.currentRPCSettingsLabel.setObjectName("currentRPCSettingsLabel")
        self.verticalLayout_2.addWidget(self.currentRPCSettingsLabel)
        self.currentRPCSettingsWidget = QtWidgets.QWidget(self.Settings)
        self.currentRPCSettingsWidget.setObjectName("currentRPCSettingsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.currentRPCSettingsWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentRPCSettingsTextBrowser = QtWidgets.QTextBrowser(self.currentRPCSettingsWidget)
        self.currentRPCSettingsTextBrowser.setObjectName("currentRPCSettingsTextBrowser")
        self.horizontalLayout.addWidget(self.currentRPCSettingsTextBrowser)
        spacerItem = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.currentRPCSettingsWidget)
        self.mainTab.addTab(self.Settings, "")
        self.verticalLayout.addWidget(self.mainTab)
        Junction.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Junction)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menuBar.setObjectName("menuBar")
        Junction.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Junction)
        self.mainToolBar.setObjectName("mainToolBar")
        Junction.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Junction)
        self.statusBar.setObjectName("statusBar")
        Junction.setStatusBar(self.statusBar)

        self.retranslateUi(Junction)
        self.mainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Junction)

    def retranslateUi(self, Junction):
        _translate = QtCore.QCoreApplication.translate
        Junction.setWindowTitle(_translate("Junction", "Junction"))
        self.walletNameLabel.setText(_translate("Junction", "Wallet name"))
        self.walletNameLineEdit.setPlaceholderText(_translate("Junction", "e.g. 2-of-3 cc trezor ledger"))
        self.requiredSignersLabel.setText(_translate("Junction", "Required Signers"))
        self.totalSignersLabel.setText(_translate("Junction", "Total Signers"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.Wallet), _translate("Junction", "Wallet"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.Devices), _translate("Junction", "Devices"))
        self.rPCUsernameLabel.setText(_translate("Junction", "RPC Username"))
        self.rPCPasswordLabel.setText(_translate("Junction", "RPC Password"))
        self.rPCHostLabel.setText(_translate("Junction", "RPC Host"))
        self.rPCHostLineEdit.setText(_translate("Junction", "127.0.0.1"))
        self.rPCPortLabel.setText(_translate("Junction", "RPC Port"))
        self.rPCPortLineEdit.setText(_translate("Junction", "18332"))
        self.currentRPCSettingsLabel.setText(_translate("Junction", "    Current RPC settings as read from file:"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.Settings), _translate("Junction", "Settings"))
